import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const initialListings = [
  {
    id: 'upkot-maskeliya-house',
    title: 'Luxury House in Upkot Maskeliya',
    propertyType: 'House',
    saleOrRent: 'Sale',
    price: 115000000,
    negotiable: true,
    city: 'Upkot, Maskeliya',
    district: 'Kandy',
    address: 'Upkot, Maskeliya',
    latitude: 6.8347,
    longitude: 80.5732,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    landSize: 40,
    landUnit: 'perches',
    houseSize: 2500,
    description: `40 perches with a 2,500 sq. ft. luxury house for sale in a high-class residential environment. Only 20 houses remain available out of 70.`,
    images: [
      '/uploads/upkotmaskeliya1(main).jpeg',
      '/uploads/upkotmaskeliya2.jpeg',
      '/uploads/upkotmaskeliya3.jpeg',
      '/uploads/upkotmaskeliya4.jpeg',
      '/uploads/upkotmaskeliya5.jpeg',
      '/uploads/upkotmaskeliya6.jpeg',
      '/uploads/upkotmaskeliya7.jpeg',
      '/uploads/upkotmaskeliya8.jpeg',
      '/uploads/upkotmaskeliya9.jpeg',
      '/uploads/upkotmaskeliya10.jpeg',
      '/uploads/upkotmaskeliya11.jpeg',
      '/uploads/upkotmaskeliya12.jpeg',
      '/uploads/upkotmaskeliya13.jpeg',
      '/uploads/upkotmaskeliya14.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'kandy-three-storey-house',
    title: 'Three-Storey House in Kandy',
    propertyType: 'House',
    saleOrRent: 'Sale',
    price: 210000000,
    negotiable: true,
    city: 'Kandy',
    district: 'Kandy',
    address: 'No. 326, George E. De Silva Mawatha, Kandy',
    latitude: 7.2783,
    longitude: 80.6321,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    landSize: 30,
    landUnit: 'perches',
    houseSize: 9589,
    description: `A three-storey house (80% complete – custom-finish ready) for sale at No. 326, George E. De Silva Mawatha, Kandy. Situated on 30 perches of land with a built-up area of approximately 9,589.2 sq. ft.`,
    images: [
      '/uploads/kandy4(main).jpeg',
      '/uploads/kandy1.jpeg',
      '/uploads/kandy2.jpeg',
      '/uploads/kandy3.jpeg',
      '/uploads/kandy5.jpeg',
      '/uploads/kandy6.jpeg',
      '/uploads/kandy7.jpeg',
      '/uploads/kandy8.jpeg',
      '/uploads/kandy9.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'ekala-house',
    title: 'House in Ekala',
    propertyType: 'House',
    saleOrRent: 'Sale',
    price: 45000000,
    negotiable: true,
    city: 'Ekala',
    district: 'Gampaha',
    address: 'Ekala, Ja-Ela',
    latitude: 7.0863,
    longitude: 79.9041,
    bedrooms: 4,
    bathrooms: 3,
    parking: 0,
    landSize: 14,
    landUnit: 'perches',
    description: `Four-bedroom house (each bedroom features a private balcony), three bathrooms, living room, main kitchen, and separate servant's kitchen/room/toilet. Situated on 14 perches of land. Includes access to Millennium City resident amenities such as the swimming pool and gym facilities.`,
    images: [
      '/uploads/ekala1(main).jpeg',
    ],
    video: '/uploads/ekala1vid.mp4',
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'kadawatha-house',
    title: 'House in Kadawatha',
    propertyType: 'House',
    saleOrRent: 'Sale',
    price: 48000000,
    negotiable: false,
    city: 'Kadawatha',
    district: 'Gampaha',
    address: 'Kirindiwela Road, Araliya Junction, Ambaruluwa, Kadawatha',
    latitude: 7.0016,
    longitude: 79.9515,
    bedrooms: 3,
    bathrooms: 0,
    parking: 0,
    landSize: 36,
    landUnit: 'perches',
    houseSize: 3500,
    description: `Newly built 3,500 sq. ft. single-storey house on 36 perches of land, located along Kirindiwela Road at Araliya Junction, Ambaruluwa (8 km from Kadawatha).`,
    images: [
      '/uploads/kadawatha12(main).jpeg',
      '/uploads/kadawatha1.jpeg',
      '/uploads/kadawatha2.jpeg',
      '/uploads/kadawatha3.jpeg',
      '/uploads/kadawatha4.jpeg',
      '/uploads/kadawatha5.jpeg',
      '/uploads/kadawatha6.jpeg',
      '/uploads/kadawatha7.jpeg',
      '/uploads/kadawatha8.jpeg',
      '/uploads/kadawatha9.jpeg',
      '/uploads/kadawatha10.jpeg',
      '/uploads/kadawatha11.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'amunugama-property',
    title: 'Property in Amunugama, Kandy',
    propertyType: 'House',
    saleOrRent: 'Sale',
    price: 40000000,
    negotiable: true,
    city: 'Amunugama',
    district: 'Kandy',
    address: 'Amunugama, Kandy',
    latitude: 7.3050,
    longitude: 80.6720,
    bedrooms: 3,
    bathrooms: 3,
    parking: 0,
    landSize: 20,
    landUnit: 'perches',
    houseSize: 3800,
    description: `20 perch 3800 sqft building space with 3 bedrooms and attached bathrooms, separate kitchenette with TV room larger living and dining area one visitor wash room and servants room and wash room. Kandy Amunugama 8km from Kandy Town.`,
    images: [
      '/uploads/amunugama1(main).jpeg',
      '/uploads/amunugama2.jpeg',
      '/uploads/amunugama3.jpeg',
      '/uploads/amunugama4.jpeg',
      '/uploads/amunugama5.jpeg',
      '/uploads/amunugama6.jpeg',
      '/uploads/amunugama7.jpeg',
      '/uploads/amunugama8.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'nugegoda-house',
    title: '3 Bedroom House with Land in Nugegoda',
    propertyType: 'House',
    saleOrRent: 'Sale',
    price: 57500000,
    negotiable: true,
    city: 'Nugegoda',
    district: 'Colombo',
    address: 'Cemetery Road, Thalapathpitiya Road, Nugegoda',
    latitude: 6.8625,
    longitude: 79.9125,
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    landSize: 12.5,
    landUnit: 'perches',
    houseSize: 1700,
    description: `3 Bedroom House with Land for Sale in Thalapathpitiya, Nugegoda. A great opportunity to purchase a valuable property in a highly convenient and peaceful residential area.`,
    images: [
      '/uploads/nugegoda7(main).jpeg',
      '/uploads/nugegoda1.jpeg',
      '/uploads/nugegoda2.jpeg',
      '/uploads/nugegoda3.jpeg',
      '/uploads/nugegoda4.jpeg',
      '/uploads/nugegoda5.jpeg',
      '/uploads/nugegoda6.jpeg',
      '/uploads/nugegoda8.jpeg',
      '/uploads/nugegoda9.jpeg',
      '/uploads/nugegoda10.jpeg',
      '/uploads/nugegoda11.jpeg',
      '/uploads/nugegoda12.jpeg',
      '/uploads/nugegoda13.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'polgolla-house',
    title: 'Brand New House at Polgolla',
    propertyType: 'House',
    saleOrRent: 'Sale',
    price: 30000000,
    negotiable: false,
    city: 'Polgolla, Katugastota',
    district: 'Kandy',
    address: 'Polgolla, Katugastota, Kandy',
    latitude: 7.3210,
    longitude: 80.6410,
    bedrooms: 3,
    bathrooms: 0,
    parking: 0,
    landSize: 10,
    landUnit: 'perches',
    description: `Katugastota, Polgolla house for sale with 3 Bedrooms. 10 Perches in total and the total amount is 30 Million.`,
    images: [
      '/uploads/polgolla1(main).jpeg',
      '/uploads/polgolla2.jpeg',
      '/uploads/polgolla3.jpeg',
      '/uploads/polgolla4.jpeg',
      '/uploads/polgolla5.jpeg',
      '/uploads/polgolla6.jpeg',
      '/uploads/polgolla7.jpeg',
      '/uploads/polgolla8.jpeg',
      '/uploads/polgolla9.jpeg',
      '/uploads/polgolla10.jpeg',
      '/uploads/polgolla11.jpeg',
      '/uploads/polgolla12.jpeg',
      '/uploads/polgolla13.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'katugastota-double-storey-house',
    title: 'Double-Storey House at Katugastota',
    propertyType: 'House',
    saleOrRent: 'Sale',
    price: 35000000,
    negotiable: true,
    city: 'Katugastota',
    district: 'Kandy',
    address: 'Balangoda Road, Katugastota, Kandy',
    latitude: 7.3310,
    longitude: 80.6250,
    bedrooms: 3,
    bathrooms: 2,
    parking: 0,
    landSize: 18.5,
    landUnit: 'perches',
    description: `Double storey house for sale on 18.5p at Balanagala road, Katugastota. 3 bedrooms, 2 bathrooms, 3 balconies, living area on both floors, electricity, and water. Located about 150 meters from the main road.`,
    images: [
      '/uploads/broad4(main).jpeg',
      '/uploads/broad1.jpeg',
      '/uploads/broad2.jpeg',
      '/uploads/broad3.jpeg',
      '/uploads/broad5.jpeg',
      '/uploads/broad6.jpeg',
      '/uploads/broad7.jpeg',
      '/uploads/broad8.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'rajagiriya-land',
    title: 'Land in Rajagiriya',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 43750000,
    pricePerPerch: 'Rs. 2.5 million per perch',
    negotiable: true,
    city: 'Rajagiriya',
    district: 'Colombo',
    address: 'Kalapuwawa, Rajagiriya',
    latitude: 6.9083,
    longitude: 79.8967,
    landSize: 17.5,
    landUnit: 'perches',
    description: `17.5 perches of land for sale at Kalapuwawa, Rajagiriya. Located 100 meters from the main road in a quiet residential neighborhood.`,
    images: [
      '/uploads/rajagiriya2(main).jpg',
      '/uploads/rajagiriya1.jpg',
      '/uploads/rajagiriya3.jpg',
      '/uploads/rajagiriya4.jpg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: false,
  },
  {
    id: 'welisara-land',
    title: 'Land in Welisara',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 42000000,
    pricePerPerch: 'Rs. 15 lakhs per perch',
    negotiable: true,
    city: 'Welisara',
    district: 'Gampaha',
    address: 'Welisara',
    latitude: 7.0270,
    longitude: 79.9048,
    landSize: 28,
    landUnit: 'perches',
    description: `Two blocks of land measuring 14.5 and 13.5 perches (28 perches total) for sale at Welisara with all basic utilities available. Conveniently located near the Kerawalapitiya Highway exit in a well-established residential area.`,
    images: [],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: false,
  },
  {
    id: 'malabe-land',
    title: 'Land in Malabe',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 21750000,
    pricePerPerch: 'Rs. 15 lakhs per perch',
    negotiable: true,
    city: 'Malabe',
    district: 'Colombo',
    address: 'Vihara Road, Malabe',
    latitude: 6.9061,
    longitude: 79.9647,
    landSize: 14.5,
    landUnit: 'perches',
    description: `14.5-perch land plot for sale on Vihara Road, Malabe. Located 500 meters from the Kottawa exit and 1 km from the main road in a peaceful residential setting.`,
    images: [],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: false,
  },
  {
    id: 'kandy-land',
    title: 'Land in Kandy',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 84000000,
    pricePerPerch: 'Rs. 4 million per perch',
    negotiable: true,
    city: 'Kandy',
    district: 'Kandy',
    address: 'Peradeniya Road, Kandy',
    latitude: 7.2950,
    longitude: 80.6380,
    landSize: 21,
    landUnit: 'perches',
    description: `21 perches of land for sale on Peradeniya Road, Kandy, near the new Damro outlet. High-visibility location suitable for commercial development.`,
    images: [
      '/uploads/pera1(main).jpg',
      '/uploads/pera2.jpg',
      '/uploads/pera3.jpg',
      '/uploads/pera4.jpg',
      '/uploads/pera5.jpg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: false,
  },
  {
    id: 'mount-lavinia-land',
    title: 'Land in Mount Lavinia',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 82500000,
    pricePerPerch: 'Rs. 5.5 Mn per perch',
    negotiable: true,
    city: 'Mount Lavinia',
    district: 'Colombo',
    address: 'No 16, College Avenue, Mount Lavinia',
    latitude: 6.8301,
    longitude: 79.8654,
    landSize: 15,
    landUnit: 'perches',
    description: `15 perches of land (offered in 2 blocks) located at No. 16, College Avenue, Mount Lavinia. Situated in a well-established residential neighborhood.`,
    images: [],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: false,
  },
  {
    id: 'panadura-land',
    title: 'Land in Panadura',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 20000000,
    negotiable: true,
    city: 'Panadura',
    district: 'Kalutara',
    address: 'Panadura',
    latitude: 6.7106,
    longitude: 79.9074,
    landSize: 17.5,
    landUnit: 'perches',
    description: `17.5 perches of land for sale in Panadura, located 50 meters from the Horana Main Road and 3 km from the Panadura Town Clock Tower.`,
    images: [],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: false,
  },
  {
    id: 'katugastota-land',
    title: 'Land in Katugastota (Kahalla)',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 80000000,
    pricePerPerch: 'Rs. 1 million per perch',
    negotiable: true,
    city: 'Katugastota',
    district: 'Kandy',
    address: 'Kahalla, Katugastota',
    latitude: 7.3275,
    longitude: 80.6219,
    landSize: 80,
    landUnit: 'perches',
    description: `80 perches of land located in Kahalla, Katugastota, featuring views of the Knuckles and Hunasgiriya mountain ranges.`,
    images: [],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: false,
  },
  {
    id: 'kurunegala-land',
    title: 'Land in Kurunegala',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 150000000,
    negotiable: true,
    city: 'Kurunegala',
    district: 'Kurunegala',
    address: 'Millāwa Housing Scheme, Kurunegala',
    latitude: 7.4863,
    longitude: 80.3647,
    landSize: 100,
    landUnit: 'perches',
    description: `100 perches of elevated land located at the Millāwa Housing Scheme, Kurunegala. Divided into 6 equal blocks (sold together).`,
    images: [],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: false,
  },
  {
    id: 'udathalawinna-thungadhura-land',
    title: '140 Perches of Land for Sale – Udathalawinna, Thungadhura',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 35000000,
    pricePerPerch: 'Rs. 250,000 per perch',
    negotiable: false,
    city: 'Udathalawinna',
    district: 'Kandy',
    address: 'Doragamuwa Main Road, Udathalawinna, Thungadhura',
    latitude: 7.3385,
    longitude: 80.6480,
    landSize: 140,
    landUnit: 'perches',
    description: `Prime 140-perch land located at Udathalawinna, Thungadhura, facing the Doragamuwa Main Road, just 8 km from Kandy town.`,
    images: [
      '/uploads/thungadhura13(main).jpeg',
      '/uploads/thungadhura1.jpeg',
      '/uploads/thungadhura2.jpeg',
      '/uploads/thungadhura3.jpeg',
      '/uploads/thungadhura4.jpeg',
      '/uploads/thungadhura5.jpeg',
      '/uploads/thungadhura6.jpeg',
      '/uploads/thungadhura7.jpeg',
      '/uploads/thungadhura8.jpeg',
      '/uploads/thungadhura9.jpeg',
      '/uploads/thungadhura10.jpeg',
      '/uploads/thungadhura11.jpeg',
      '/uploads/thungadhura12.jpeg',
      '/uploads/thungadhura14.jpeg',
      '/uploads/thungadhura15.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'kalutara-estate-land',
    title: 'Exclusive Eco/Agro Tourism Estate for Sale-Bulathsinhala',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 150000000,
    negotiable: true,
    city: 'Bulathsinhala',
    district: 'Kalutara',
    address: 'Bulathsinhala, Kalutara',
    latitude: 6.6478,
    longitude: 80.1458,
    landSize: 14.5,
    landUnit: 'acres',
    description: `14.5-acre scenic agricultural estate located in Bulathsinhala, Kalutara. 8.5 acres tea, 2.5 acres rubber, 100+ mature coconut trees.`,
    images: [
      '/uploads/kaluthara1(main).jpeg',
      '/uploads/kaluthara2.jpeg',
      '/uploads/kaluthara3.jpeg',
      '/uploads/kaluthara4.jpeg',
      '/uploads/kaluthara5.jpeg',
      '/uploads/kaluthara6.jpeg',
      '/uploads/kaluthara7.jpeg',
      '/uploads/kaluthara8.jpeg',
      '/uploads/kaluthara9.jpeg',
      '/uploads/kaluthara10.jpeg',
      '/uploads/kaluthara11.jpeg',
      '/uploads/kaluthara12.jpeg',
      '/uploads/kaluthara13.jpeg',
      '/uploads/kaluthara14.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'nillamba-estate-land',
    title: 'Nillamba Estate',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 4125000,
    pricePerPerch: 'Rs. 150,000 per perch',
    negotiable: true,
    city: 'Nillamba',
    district: 'Kandy',
    address: 'Nillamba (17km to Peradeniya town)',
    latitude: 7.1850,
    longitude: 80.6025,
    landSize: 27.5,
    landUnit: 'perches',
    description: `27.5 perches of land located in Nillamba, 17 km from Peradeniya town, situated below Hotel Club Lespri. Includes clear deeds.`,
    images: [
      '/uploads/nillamba1(main).jpeg',
      '/uploads/nillamba2.jpeg',
      '/uploads/nillamba3.jpeg',
      '/uploads/nillamba4.jpeg',
      '/uploads/nillamba5.jpeg',
      '/uploads/nillamba6.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'katugastota-station-road-land',
    title: 'Land in Katugastota (Station Road)',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 36000000,
    pricePerPerch: 'Rs. 900,000 per perch',
    negotiable: false,
    city: 'Katugastota',
    district: 'Central Province',
    address: 'Station Road, Katugastota, Kandy',
    latitude: 7.3275,
    longitude: 80.6219,
    landSize: 40,
    landUnit: 'perches',
    description: `4 blocks, Each 10 perches, Station road katugastota, kandy. 600 meters from the main road.`,
    images: [
      '/uploads/katugastota7(main).jpeg',
      '/uploads/katugastota1.jpeg',
      '/uploads/katugastota2.jpeg',
      '/uploads/katugastota3.jpeg',
      '/uploads/katugastota4.jpeg',
      '/uploads/katugastota5.jpeg',
      '/uploads/katugastota6.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'wattegama-land',
    title: 'Prime 130-Perch Scenic Property in Wattegama, Kandy',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 15000000,
    negotiable: false,
    city: 'Wattegama',
    district: 'Kandy',
    address: 'Wattegama, Kandy',
    latitude: 7.3502,
    longitude: 80.7015,
    landSize: 130,
    landUnit: 'perches',
    description: `Looking for the ultimate location for a luxury boutique hotel, eco-resort, or your dream private sanctuary? 130 Perches with panoramic Hunnasgiriya views.`,
    images: [
      '/uploads/wattegama9(main).jpg',
      '/uploads/wattegama1.jpg',
      '/uploads/wattegama2.jpg',
      '/uploads/wattegama3.jpg',
      '/uploads/wattegama4.jpg',
      '/uploads/wattegama5.jpg',
      '/uploads/wattegama6.jpg',
      '/uploads/wattegama7.jpg',
      '/uploads/wattegama8.jpg',
      '/uploads/wattegama10.jpg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'hikkaduwa-house',
    title: 'Rare Property for Sale – Hikkaduwa',
    propertyType: 'House',
    saleOrRent: 'Sale',
    price: 70000000,
    negotiable: true,
    city: 'Hikkaduwa',
    district: 'Galle',
    address: 'Hikkaduwa–Baddegama Road, Hikkaduwa',
    latitude: 6.1395,
    longitude: 80.1063,
    bedrooms: 4,
    bathrooms: 0,
    parking: 0,
    landSize: 17.3,
    landUnit: 'perches',
    description: `A unique opportunity to own a charming ancestral/traditional house situated on 17.3 perches of valuable land along Hikkaduwa–Baddegama Road. 100 meters to Beach.`,
    images: [
      '/uploads/hikkaduwa3(main).jpeg',
      '/uploads/hikkaduwa1.jpeg',
      '/uploads/hikkaduwa2.jpeg',
      '/uploads/hikkaduwa4.jpeg',
      '/uploads/hikkaduwa5.jpeg',
      '/uploads/hikkaduwa6.jpeg',
      '/uploads/hikkaduwa7.jpeg',
      '/uploads/hikkaduwa8.jpeg',
      '/uploads/hikkaduwa9.jpeg',
      '/uploads/hikkaduwa10.jpeg',
    ],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'katukithula-nuwaraeliya-land',
    title: 'Prime 400-Perch Investment Opportunity – Katukithula, Nuwara Eliya',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 64000000,
    pricePerPerch: 'Rs. 160,000 per perch',
    negotiable: true,
    city: 'Katukithula',
    district: 'Nuwara Eliya',
    address: 'Glenloch Group-A, Katukithula, Nuwara Eliya Road',
    latitude: 6.9700,
    longitude: 80.7500,
    landSize: 400,
    landUnit: 'perches',
    description: `A rare tourism & hospitality investment opportunity — 400 perches (2.5 acres) of prime land at Glenloch Group-A, Nuwara Eliya Road, Katukithula. Positioned along Pekoe Trail Stage 3.`,
    images: [],
    video: '/uploads/katukithula.mp4',
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: true,
  },
  {
    id: 'athurugiriya-land',
    title: 'Prime Land for Sale – Athurugiriya',
    propertyType: 'Land',
    saleOrRent: 'Sale',
    price: 14690000,
    pricePerPerch: 'Rs. 650,000 per perch',
    negotiable: true,
    city: 'Athurugiriya',
    district: 'Colombo',
    address: 'Mailangamuwa Road, Athurugiriya',
    latitude: 6.8789,
    longitude: 79.9956,
    landSize: 22.6,
    landUnit: 'perches',
    description: `Two valuable residential land blocks for sale in Athurugiriya — ideal for investment or home building. Block 01: 9.8P, Block 02: 12.8P.`,
    images: [],
    contactPhone: '0777801470',
    contactEmail: 'admin@boamrealtors.lk',
    status: 'PUBLISHED' as const,
    isFeatured: false,
  },
];

async function main() {
  const email = process.env.ADMIN_EMAIL || 'admin@boamrealtors.lk';
  const password = process.env.ADMIN_PASSWORD || 'BoamAdmin2026!';
  const fullName = process.env.ADMIN_NAME || 'BOAM System Admin';

  console.log(`⏳ Ensuring admin user exists: ${email}...`);
  const salt = await bcrypt.genSalt(10);
  const hashedPassword = await bcrypt.hash(password, salt);

  const admin = await prisma.user.upsert({
    where: { email },
    update: {
      role: 'ADMIN',
      password: hashedPassword,
      isEmailVerified: true,
      isActive: true,
    },
    create: {
      fullName,
      email,
      password: hashedPassword,
      role: 'ADMIN',
      isEmailVerified: true,
      isActive: true,
    },
  });

  console.log(`✅ Admin account confirmed (ID: ${admin.id})`);
  console.log(`⏳ Seeding all 23 listings into PostgreSQL...`);

  let seededCount = 0;
  for (const item of initialListings) {
    const { id, ...data } = item;
    await prisma.property.upsert({
      where: { id },
      update: {
        ...data,
        userId: admin.id,
      },
      create: {
        id,
        ...data,
        userId: admin.id,
      },
    });
    seededCount++;
  }

  console.log(`🎉 Successfully seeded ${seededCount} listings into the database!`);
  const totalInDb = await prisma.property.count();
  console.log(`📊 Total listings in Database now: ${totalInDb}`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding listings:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
